image: python:3.12

stages:
  - lint

lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install pep8-naming
    - flake8 --verbose

black-check:
  stage: format
  image: gitlab.com/pipeline-components/black@1.0.0
  script:
    - black --check --verbose lyceum/