image: python:3.12

stages:
  - lint

lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install pep8-naming
    - pip install flake8-quotes
    - pip install flake8-import-order
    - flake8 lyceum

black:
  stage: lint
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --skip-string-normalization lyceum