stages:
  - lint
  - format

lint:
  stage: lint
  image: python:3.12
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements/prod.txt
    - pip install flake8 flake8-import-order flake8-quotes pep8-naming
  script:
    - flake8 . --config=.flake8 
  only:
    - merge_requests
    - main

black:
  stage: format
  image: python:3.12
  before_script:
    - python -m pip install --upgrade pip
    - pip install black==24.8.*
  script:
    - black --check --diff .
  only:
    - merge_requests
    - main