# Generated by Django 5.2 on 2026-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        help_text='max 150 символов',
                        max_length=150,
                        verbose_name='имя',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Напишите в этом поле все то, что хотели бы сказать разработчикам',
                        verbose_name='обратная связь',
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='время создания'
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        help_text='max 150 символов',
                        max_length=150,
                        verbose_name='почта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
    ]
