# Generated by Django 5.2 on 2026-03-13 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратные связи',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'получено'),
                    ('processing', 'в обработке'),
                    ('answered', 'ответ дан'),
                ],
                default='received',
                max_length=20,
                verbose_name='статус',
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(max_length=150, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='имя'
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='обратная связь'),
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'from_status',
                    models.CharField(db_column='from', max_length=20),
                ),
                ('to_status', models.CharField(db_column='to', max_length=20)),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='feedback.feedback',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
        ),
    ]
