# Generated by Django 5.2 on 2026-03-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_feedback_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={
                'verbose_name': 'Статус логи',
                'verbose_name_plural': 'Статус логи',
            },
        ),
    ]
