# Generated by Django 5.2 on 2026-03-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_statuslog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuslog',
            old_name='to_status',
            new_name='to',
        ),
    ]
