# Generated by Django 5.2 on 2026-03-15 16:51

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_to_status_statuslog_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPersonalData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='имя'
                    ),
                ),
                (
                    'mail',
                    models.EmailField(max_length=150, verbose_name='почта'),
                ),
            ],
            options={
                'verbose_name': 'персональные данные',
                'verbose_name_plural': 'персональные данные',
            },
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'file',
                    models.FileField(
                        upload_to=feedback.models.get_upload_path,
                        verbose_name='файл',
                    ),
                ),
                (
                    'feedback',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='files',
                        to='feedback.feedback',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='personal_data',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='feedback.feedbackpersonaldata',
                verbose_name='персональные данные',
            ),
        ),
    ]
