# Generated by Django 5.2 on 2026-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Количество попыток сварить кофе',
                verbose_name='количество сваренных чашек кофе',
            ),
        ),
    ]
