# Generated by Django 5.2 on 2026-03-22 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('users', '0002_alter_profile_coffee_count'),
        ('users', '0003_alter_profile_options_alter_profile_user'),
    ]

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Количество попыток сварить кофе',
                verbose_name='количество сваренных чашек кофе',
            ),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь',
            ),
        ),
    ]
