# Generated by Django 5.2 on 2026-03-22 16:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'users',
            '0002_alter_profile_coffee_count_squashed_0003_alter_profile_options_alter_profile_user',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attemps_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='попыток входа'
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='block_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='дата блокировки'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(
                blank=True, null=True, verbose_name='дата рождения'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.PositiveIntegerField(
                default=0, verbose_name='чашки кофе'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.Profile.image_path,
                verbose_name='аватарка',
            ),
        ),
    ]
