# Generated by Django 5.2 on 2026-03-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_attemps_count_profile_block_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='attemps_count',
            new_name='attempts_count',
        ),
    ]
