# Generated by Django 5.2 on 2026-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_attemps_count_profile_attempts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(
                blank=True,
                default='',
                help_text='расскажите что-то',
                verbose_name='о себе',
            ),
        ),
    ]
