# Generated by Django 5.2 on 2026-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(
                blank=True, default='', verbose_name='о себе'
            ),
        ),
    ]
