# Generated by Django 5.2 on 2026-03-27 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_item_text'),
        ('rating', '0002_alter_rating_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
            },
        ),
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratings',
                to='catalog.item',
                verbose_name='товар',
            ),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(
                choices=[
                    ('', '— Без оценки —'),
                    (1, 'Ненависть'),
                    (2, 'Неприязнь'),
                    (3, 'Нейтрально'),
                    (4, 'Обожание'),
                    (5, 'Любовь'),
                ],
                verbose_name='оценка',
            ),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ratings',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
