# Generated by Django 5.2 on 2026-03-27 19:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_item_text'),
        ('rating', '0003_alter_rating_options_alter_rating_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(
                choices=[
                    ('', '— Без оценки —'),
                    (1, 'Ненависть'),
                    (2, 'Неприязнь'),
                    (3, 'Нейтрально'),
                    (4, 'Обожание'),
                    (5, 'Любовь'),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name='оценка',
            ),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(
                fields=('user', 'item'), name='unique_user_item_rating'
            ),
        ),
    ]
