# Generated by Django 5.2 on 2026-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_rate',
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name='дата оценки'
            ),
        ),
    ]
