# Generated by Django 5.2 on 2026-02-19 18:43

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('catalog', '0001_initial'),
        ('catalog', '0002_alter_category_slug_alter_tag_slug'),
        ('catalog', '0003_alter_item_options_item_category_item_tags'),
        ('catalog', '0004_alter_category_options_alter_tag_options_and_more'),
        ('catalog', '0005_alter_item_name_alter_item_tags'),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='Название'),
                ),
                (
                    'slug',
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name='Слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='Вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='Название'),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name='Слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='max 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='Название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Описание должно быть больше, чем из 2х слов и содержать слова "превосходно, роскошно" ',
                        validators=[catalog.validators.validate_brilliant],
                        verbose_name='Текст',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text='Выберите категорию',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.category',
                        verbose_name='Категории',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        help_text='Выберите теги',
                        to='catalog.tag',
                        verbose_name='Теги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
