# Generated by Django 5.2 on 2026-02-21 17:54

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="статус публикации",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "cannonical_name",
                    models.CharField(
                        editable=False,
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое название",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Максимум 200 символов",
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name="слаг",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        help_text="Max 32767",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name="вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="статус публикации",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "cannonical_name",
                    models.CharField(
                        editable=False,
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое название",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="слаг",
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name="слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
                "default_related_name": "tags",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="max 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="статус публикации",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "cannonical_name",
                    models.CharField(
                        editable=False,
                        help_text="Каноническое название элемента",
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="каноническое название",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Описание должно быть больше, чем из 2х слов и содержать слова \"превосходно, роскошно\"",
                        validators=[
                            catalog.validators.WordsValidator(
                                "превосходно", "роскошно"
                            )
                        ],
                        verbose_name="описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                ("tags", models.ManyToManyField(to="catalog.tag")),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "default_related_name": "items",
            },
        ),
    ]
