# Generated by Django 5.2 on 2026-02-20 07:49

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус публикации',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='max 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='слаг',
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        help_text='вес',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус публикации',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='max 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='слаг',
                        max_length=200,
                        unique=True,
                        validators=[catalog.validators.validate_slug],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='статус публикации',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='max 150 символов',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Описание должно быть больше, чем из 2х слов и содержать слова "превосходно, роскошно" ',
                        validators=[catalog.validators.validate_brilliant],
                        verbose_name='текст',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text='Выберите категорию',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='catalog.category',
                        verbose_name='категория',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        help_text='Выберите теги',
                        to='catalog.tag',
                        verbose_name='теги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
