# Generated by Django 5.2 on 2026-02-17 18:10

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='Название'),
                ),
                (
                    'slug',
                    models.CharField(
                        max_length=200, unique=True, verbose_name='Слаг'
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='Вес',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='Название'),
                ),
                (
                    'text',
                    models.TextField(
                        validators=[catalog.validators.validate_brilliant],
                        verbose_name='Текст',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=150, verbose_name='Название'),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        max_length=200, unique=True, verbose_name='Слаг'
                    ),
                ),
            ],
        ),
    ]
