# Generated by Django 5.2 on 2026-02-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ('weight', 'id'),
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
