# Generated by Django 5.2 on 2026-02-17 18:45

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name='Слаг',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name='Слаг',
            ),
        ),
    ]
