# Generated by Django 5.2 on 2026-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(
                default='', editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name='tag',
            name='normalized_name',
            field=models.CharField(
                default='', editable=False, max_length=100, unique=True
            ),
        ),
    ]
