# Generated by Django 5.2 on 2026-02-22 21:00

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Описание должно быть больше, чем из 2х слов и содержать слова: превосходно, роскошно",
                validators=[
                    catalog.validators.WordsValidator(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
