# Generated by Django 5.2 on 2026-02-19 08:49

import catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_item_options_item_category_item_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='Категории',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='max 150 символов',
                max_length=150,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.tag', verbose_name='Теги'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='Описание должно быть больше, чем из 2х слов и содержать слова "превосходно, роскошно" ',
                validators=[catalog.validators.validate_brilliant],
                verbose_name='Текст',
            ),
        ),
    ]
