# Generated by Django 5.2 on 2026-02-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0004_remove_item_cannonical_name_alter_category_slug_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='catalog/gallery/',
                        verbose_name='изображение',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='gallery_images',
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'изображение галереи',
                'verbose_name_plural': 'изображения галереи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='catalog/main/',
                        verbose_name='главное изображение',
                    ),
                ),
                (
                    'item',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='main_image',
                        to='catalog.item',
                        verbose_name='товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'главное изображение',
                'verbose_name_plural': 'главные изображения',
            },
        ),
    ]
