# Generated by Django 5.2 on 2026-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='max 150 символов',
                max_length=150,
                unique=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                help_text='Выберите теги',
                to='catalog.tag',
                verbose_name='Теги',
            ),
        ),
    ]
