# Generated by Django 5.2 on 2026-02-19 20:09

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('catalog', '0006_alter_category_options_alter_item_options_and_more'),
        (
            'catalog',
            '0007_alter_category_is_published_alter_category_slug_and_more',
        ),
    ]

    dependencies = [
        ('catalog', '0005_alter_item_name_alter_item_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='статус публикации',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='max 150 символов',
                max_length=150,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(
                help_text='слаг',
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                help_text='вес',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='вес',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='max 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                help_text='Выберите теги',
                to='catalog.tag',
                verbose_name='теги',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                help_text='Описание должно быть больше, чем из 2х слов и содержать слова "превосходно, роскошно" ',
                validators=[catalog.validators.validate_brilliant],
                verbose_name='текст',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='статус публикации',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='статус публикации',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='max 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(
                help_text='слаг',
                max_length=200,
                unique=True,
                validators=[catalog.validators.validate_slug],
                verbose_name='слаг',
            ),
        ),
    ]
