# Generated by Django 5.2 on 2026-02-27 17:55

import catalog.validators
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0007_alter_item_text"),
        ("catalog", "0008_alter_item_text"),
        ("catalog", "0009_alter_item_text"),
    ]

    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Описание должно быть больше, чем из 2х слов лоль и  содержать слова: превосходно, роскошно",
                validators=[
                    catalog.validators.WordsValidator(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
