# Generated by Django 5.2 on 2026-02-27 16:29

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Описание должно быть больше, чем из 2х слов лоль и содержать слова: превосходно, роскошно",
                validators=[
                    catalog.validators.WordsValidator(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
    ]
