# Generated by Django 5.2 on 2026-02-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0006_alter_category_options_alter_item_options_and_more_squashed_0007_alter_category_is_published_alter_category_slug_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='max 150 символов',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
    ]
