# Generated by Django 5.2 on 2026-03-09 14:19

import catalog.models
import core.models
import catalog.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        (
            "catalog",
            "0010_alter_mainimage_image_alter_mainimage_item_image_and_more",
        ),
        (
            "catalog",
            "0011_item_is_on_main_alter_category_canonical_name_and_more",
        ),
        ("catalog", "0012_item_created_item_updated"),
        ("catalog", "0013_alter_item_created_alter_item_updated"),
    ]

    dependencies = [
        ("catalog", "0007_alter_item_text_squashed_0009_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                default=None,
                upload_to=core.models.item_directory_path,
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        upload_to=core.models.item_directory_path,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото",
                "verbose_name_plural": "фото",
            },
        ),
        migrations.DeleteModel(
            name="Images",
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="отображение на главной"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="canonical_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Каноническое название элемента",
                max_length=150,
                unique=True,
                verbose_name="каноническое название",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
                verbose_name="Изображения",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Описание должно быть больше, чем из 2х слов и  содержать слова: превосходно, роскошно",
                validators=[
                    catalog.validators.WordsValidator(
                        "превосходно", "роскошно"
                    )
                ],
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
                verbose_name="Главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="canonical_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Каноническое название элемента",
                max_length=150,
                unique=True,
                verbose_name="каноническое название",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время изменения"
            ),
        ),
    ]
