# Generated by Django 5.2 on 2026-02-28 15:16

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_item_text_squashed_0009_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(
                default=None,
                upload_to=catalog.models.item_directory_path,
                verbose_name='изображение',
            ),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                to='catalog.item',
            ),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        default=None,
                        upload_to=catalog.models.item_directory_path,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='catalog.item',
                    ),
                ),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
