# Generated by Django 5.2 on 2026-03-06 16:39

import catalog.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0010_alter_mainimage_image_alter_mainimage_item_image_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(
                default=False, verbose_name='отображение на главной'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='canonical_name',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Каноническое название элемента',
                max_length=150,
                unique=True,
                verbose_name='каноническое название',
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='images',
                to='catalog.item',
                verbose_name='Изображения',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text='Описание должно быть больше, чем из 2х слов и  содержать слова: превосходно, роскошно',
                validators=[
                    catalog.validators.WordsValidator(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='описание',
            ),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='main_image',
                to='catalog.item',
                verbose_name='Главное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='canonical_name',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Каноническое название элемента',
                max_length=150,
                unique=True,
                verbose_name='каноническое название',
            ),
        ),
    ]
