# Generated by Django 5.2 on 2026-03-11 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_image_item_alter_mainimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                help_text='Максимум 32767',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='вес',
            ),
        ),
    ]
